### PR TITLE
nospecialize in displaying SOneTo

### PR DESCRIPTION
**Pull request by jishnub**

### CODE REVIEW

**Comment by mateuszbaran** [comment]
For some weird reason this makes printing slower?
Current StaticArrays:
```julia
julia> @time repr(SOneTo(3))
  0.002636 seconds (20 allocations: 1.133 KiB, 99.22% compilation time)
"SOneTo(3)"

julia> @time repr(SOneTo(4))
  0.004234 seconds (20 allocations: 1.133 KiB, 99.47% compilation time)
"SOneTo(4)"

julia> function Base.show(io::IO, @nospecialize(x::SOneTo))
           print(io, "SOneTo(", length(x)::Int, ")")
       end

julia> @time repr(SOneTo(3))
  0.007384 seconds (1.04 k allocations: 71.046 KiB, 99.67% compilation time)
"SOneTo(3)"

julia> @time repr(SOneTo(4))
  0.000025 seconds (7 allocations: 344 bytes)
"SOneTo(4)"

```

**Comment by jishnub** [comment]
I'd say that this PR improves things, as the compilation happens only once, and subsequent calls are fast

**Comment by jishnub** [comment]
Gentle bump

**Comment by mateuszbaran** [comment]
#1187 is now merged so I think we could add printing of `SOneTo` to `compile_workload` and it would be completely fine.

**Comment by jishnub** [comment]
I'm unsure what's the best way to address this, as `show(IOBuffer(), SOneTo(1))` doesn't precompile it for displaying to a terminal. What works is `show(SOneTo(1))`, but this writes to the terminal during precompilation. I've tried to redirect the stdin to `devnull`, but this leads to an error on my system.

**Comment by mateuszbaran** [comment]
I think you should redirect stdout, not stdin. Like this:
```julia
redirect_stdout(devnull) do
    show(SOneTo(1))
end
```
in the workload.

**Comment by jishnub** [comment]
Thanks for catching that! Oddly, adding this doesn't improve the compilation time. I wonder if this is because the display to `Base.TTY` is not compiled when the output is redirected to `devnull`, which is a `Base.DevNull`

**Comment by mateuszbaran** [comment]
I see. Well, let's merge this then without precompilation.

**Review by mateuszbaran — APPROVED** [review]

**Pull request merged**
