### PR TITLE
Minor changes and cleanups

### PR DESCRIPTION
**Pull request by c42f**
* Avoid Travis timouts by removing outer testset
* Remove obsolete, hacky workaround for inference issue in 0.6-

### CODE REVIEW

**Comment by c42f** [comment]
@bshall I'm afraid this will introduce some minor conflicts for your PR, but I want to get this quick fix in right away, as our tests are generally timing out on Travis :-/

**Comment by c42f** [comment]
Ok... I guess I need to try fixing julia-0.7... or at least disable it in Travis.  The failed CI is really distracting.

**Comment by KristofferC** [comment]
Just allow failures on 0.7?

**Comment by c42f** [comment]
Good point.  The failure seems localized so I hope it can be sorted out.  It seems to be the following:

```julia
julia> @code_warntype StaticArrays.index_sizes(Size(2,2), :, :)
Variables:
  #self#::StaticArrays.#index_sizes
  s::StaticArrays.Size{(2, 2)}
  #unused#::Colon
  inds::Tuple{Colon}

Body:
  begin
      return (Core.tuple)($(QuoteNode(Size(2,))), $(QuoteNode(Size(2,))))::Tuple{StaticArrays.Size{(2,)},Any}
  end::Tuple{StaticArrays.Size{(2,)},Any}
```

**Pull request merged**
