### PR TITLE
Fix #356, Performance of SMatrix(::StaticMatrix)

### LINKED ISSUE #356: Performance of SMatrix(::StaticMatrix)
```julia
using StaticArrays, BenchmarkTools
m = rand(SMatrix{3, 3})
@btime SMatrix($m)
```
results in 2.470 μs (33 allocations: 1.94 KiB). This particular use case is not so interesting, but this method also creates an `SMatrix` from  other `StaticMatrix` types, which is occasionally useful. PR coming.

### PR DESCRIPTION
**Pull request by tkoolen**
Fixes https://github.com/JuliaArrays/StaticArrays.jl/issues/356.

### CODE REVIEW

**Comment by c42f** [comment]
This fix looks functional, but perhaps we should just be deleting this method entirely, and fixing the equivalent `SArray` constructor instead?

(This has the feeling of a lot of other issues we've had in `StaticArrays` ever since `SMatrix` became a simple type alias of `SArray`.)

**Comment by tkoolen** [comment]
I finally got around to this again. What do you think of the new approach?

It currently requires defining a `convert_similar_type` method for each `StaticArray` subtype that needs to work with these generic `StaticArray` constructor methods. I wanted to just use `similar_type`, but for this purpose it's too inconsistent in whether it returns an `MArray` or `SArray` type. Unfortunately, it's not possible to define `convert_similar_type` generically for all possible subtypes of `StaticArray`, because in general it isn't even known how many type parameters any given concrete `StaticArray` subtype has.

**Comment by andyferris** [comment]
OK, interesting approach. I can see that we need *something* like this. (I wonder if Julia v0.7 includes any implementation for controlling eltypes for `AbstractArray`?)

> Unfortunately, it's not possible to define convert_similar_type generically for all possible subtypes of StaticArray, because in general it isn't even known how many type parameters any given concrete StaticArray subtype has.

We used to have a hilarious implementation for exactly this, that would analyze the type tree to the point where it could replace exactly the correct type parameters as necessary. :)

**Comment by c42f** [comment]
It looks like #356 was closed by taking a much more minimal approach in #358. Should we close this issue?

**Comment by tkoolen** [comment]
Sure.

**Pull request closed without merging**
