### PR TITLE
Fix indexing with zero-size arrays

### PR DESCRIPTION
**Pull request by Keno**

### CODE REVIEW

**Comment by andyferris** [comment]
Looks good - thanks @Keno.

Out of curiosity, under what circumstances did you note this? It probably doesn't happen often that you *need* a vector of known length equal to zero...

**Comment by Keno** [comment]
Celeste has index sets for different objects (stars/galaxies) which through complicated abstractions end up as svectors of indicies when indexing into a hessian. The shape parameters for stars are empty (because they're point sources), but I don't check for that case in the generic code that does both.

**Comment by andyferris** [comment]
Aha, thanks for the explanation.

**Comment by andyferris** [comment]
Was the trailing singletons issue (#125) also related to Celeste/other working code, or just a curiosity?

**Comment by Keno** [comment]
Yes, it is. There's one more issue which is that the new version of this code blows up type inference. I have a fix coming for that as well, but that'll have to wait until tomorrow.

**Comment by Keno** [comment]
This code meaning StaticArrays, not this PR

**Comment by andyferris** [comment]
I look forward to it

**Pull request merged**
