### PR TITLE
Ensure we test on 1.5

### PR DESCRIPTION
**Pull request by c42f**
https://github.com/JuliaArrays/StaticArrays.jl/pull/838#issuecomment-709031044

### CODE REVIEW

**Review by andyferris — APPROVED** [review]

**Comment by andyferris** [comment]
Why do the tests take so long?

**Comment by c42f** [comment]
Wow, that failure on windows is concerning. Somehow we've got a C++ exception getting reported there, along with a Julia stack trace. It looks like the program ran out of memory in some C++ code (presumably the Julia runtime?) and threw `std::bad_alloc`, leading to `abort` being called https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/abort?view=vs-2019 and returning an exit code of 3.

```
signal (22): SIGABRT
in expression starting at D:\a\StaticArrays.jl\StaticArrays.jl\test\lu.jl:51
raise at C:\windows\System32\msvcrt.dll (unknown line)
abort at C:\windows\System32\msvcrt.dll (unknown line)
ZN9__gnu_cxx27__verbose_terminate_handlerEv at C:\hostedtoolcache\windows\julia\1.5.2\x86\bin\libstdc++-6.dll (unknown line)
ZGTtNSt16invalid_argumentD2Ev at C:\hostedtoolcache\windows\julia\1.5.2\x86\bin\libstdc++-6.dll (unknown line)
ZGTtNSt16invalid_argumentD2Ev at C:\hostedtoolcache\windows\julia\1.5.2\x86\bin\libstdc++-6.dll (unknown line)
Allocations: 2805643639 (Pool: 2805283867; Big: 359772); GC: 1229
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
ERROR: Package StaticArrays errored during testing (exit code: 3)
Stacktrace:
 [1] pkgerror(::String) at D:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.5\Pkg\src\Types.jl:52
 [2] test(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}; coverage::Bool, julia_args::Cmd, test_args::Cmd, test_fn::Nothing) at D:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.5\Pkg\src\Operations.jl:1578
 [3] test(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}; coverage::Bool, test_fn::Nothing, julia_args::Cmd, test_args::Cmd, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at D:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.5\Pkg\src\API.jl:327
 [4] #test#61 at D:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.5\Pkg\src\API.jl:67 [inlined]
 [5] test(; name::Nothing, uuid::Nothing, version::Nothing, url::Nothing, rev::Nothing, path::Nothing, mode::Pkg.Types.PackageMode, subdir::Nothing, kwargs::Base.Iterators.Pairs{Symbol,Bool,Tuple{Symbol},NamedTuple{(:coverage,),Tuple{Bool}}}) at D:\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.5\Pkg\src\API.jl:80
 [6] top-level scope at none:1
Error: Process completed with exit code 1.
```

> Why do the tests take so long?

I think because we stress the compiler a lot by compiling so many specializations. The LU tests alone take 60 s on my machine.

**Comment by c42f** [comment]
The ubuntu failures on nightly are some oddities I've seen before (in unrelated packages)... some weird error during git cloning the package.

**Comment by c42f** [comment]
Nightly failure during git clone reported at https://github.com/julia-actions/julia-buildpkg/issues/7

**Comment by c42f** [comment]
Well, it seems this regularly runs out of memory on windows with Julia 1.5.  Whether that's because the testing environment is very memory limited, or we've got some horrible bug is unclear.

Need to test on a windows box...

**Comment by c42f** [comment]
I ran manually on windows with julia 1.5.3 and tests passed. So I think the errors here are likely due to the test environment resources.

**Comment by mateuszbaran** [comment]
This was handled in https://github.com/JuliaArrays/StaticArrays.jl/pull/928 so I think we can close this PR.

**Pull request closed without merging**
