### PR TITLE
Add `Base.dataids(::SArray)`

### PR DESCRIPTION
**Pull request by martinholters**
An `SArray` can never alias anything, so it is safe to return an empty tuple here and prevent the aliasing detection machinery from doing unnecessary work.

### CODE REVIEW

**Comment by martinholters** [comment]
I'm a bit unsure about a good way to test this.
```julia
if isdefined(Base, :dataids) # v0.7-
    @test Base.dataids(SVector((rand(10)...,))) === ()
end
```
seems a bit tautological. OTOH, `Base.unalias(a, b::SArray) === b` should be true no matter the definition of `dataids`. Opinions?

**Comment by martinholters** [comment]
> What should we do about `MArray` and `SizedArray`?

Good point. The default is to use the `objectid`. For a mutable type (`MArray`) this is its hashed memory address. That's ok because two `MArrays` alias if and only if they are identical, and they cannot alias any other objects, unless these wrap them. In that case, the wrapping object is responsible for including the wrapped objects `dataids` in its own `dataids`. (Although it looks like this is at present only the case for a subset of the wrappers in Base.) However, calling `pointer` directly should work equally well and seems to be slightly faster.

OTOH, `SizedArray` indeed should provide a specialized `dataids`, returning the `dataids` of the internal backing `Array`.

I'll update accordingly and add some tests.

**Comment by martinholters** [comment]
The new tests all passed on 0.7 before later tests caused the known failures.

**Comment by andyferris** [comment]
Thanks :)

**Pull request merged**
