### PR TITLE
Added an `eigvals` specialization

### PR DESCRIPTION
**Pull request by nonasoumy**
Cheaper to calculate eigenvalues too
Added test cases for block-diagonal 3x3 matrices that expose holes in
the 3x3 eigenvector routines. Need to find a way of specializing these.

### CODE REVIEW

**Comment by tkoolen** [comment]
@SimonDanisch, he's PRing random branches *from JuliaArrays/StaticArrays.jl*. Don't delete the branches, they might still contain useful commits.

**Comment by SimonDanisch** [comment]
Oh woops, sorry ;)

**Comment by tkoolen** [comment]
The account was created 3 days ago and has since opened 140 PRs like this. Probably a bot. Can you [block this user](https://help.github.com/articles/blocking-a-user-from-your-organization/)? I don't have permission to do so.

**Comment by SimonDanisch** [comment]
Ah now I also see, that those are "our own" commits... Weird!

**Comment by SimonDanisch** [comment]
I blocked the account!

**Pull request closed without merging**
