### PR TITLE
Update CI for Julia 1.4

### PR DESCRIPTION
**Pull request by andyferris**

### CODE REVIEW

**Comment by andyferris** [comment]
What are the three (required) checks at the bottom? How do we change them to Julia 1.4?

**Comment by tkf** [comment]
I think that's the status check I requested https://github.com/JuliaArrays/StaticArrays.jl/pull/776#issuecomment-623044559

I don't have access to it, but I think that's in https://github.com/JuliaArrays/StaticArrays.jl/settings/branches

**Comment by c42f** [comment]
Oh that was confusing. I wish the required checks were maintained as part of a yml config and not hidden away in the admin interface :-/

**Comment by c42f** [comment]
Ok, I've updated the config and merged this at the same time to hopefully prevent other PRs from becoming broken.

**Comment by andyferris** [comment]
> I wish the required checks were maintained as part of a yml config and not hidden away in the admin interface :-/

Hmm... I guess you even could self-refrentially maintain a branch protection on the branch itself? Have github check the config prior to a change to check if the pusher has privileges?

**Pull request merged**
