### PR TITLE
Allow failures on nightly.

### PR DESCRIPTION
**Pull request by tkoolen**

### CODE REVIEW

**Comment by tkoolen** [comment]
Not that I know of for https://travis-ci.org/JuliaArrays/StaticArrays.jl/jobs/527128997#L728. 

On OSX (more recent version than what Travis uses), I'm getting

```julia
ERROR: Error while loading expression starting at /Users/tkoolen/.julia/packages/StaticArrays/VyRz3/test/runtests.jl:1
caused by [exception 2]
InitError during initialization of module SpecialFunctions
Stacktrace:
 [1] _include_from_serialized(::String, ::Array{Any,1}) at ./loading.jl:685
 [2] _require_search_from_serialized(::Base.PkgId, ::String) at ./loading.jl:765
 [3] _require(::Base.PkgId) at ./loading.jl:990
 [4] require(::Base.PkgId) at ./loading.jl:911
 [5] require(::Module, ::Symbol) at ./loading.jl:906
 [6] include at ./boot.jl:328 [inlined]
 [7] include_relative(::Module, ::String) at ./loading.jl:1094
 [8] include(::Module, ::String) at ./Base.jl:31
 [9] include(::String) at ./client.jl:431
 [10] top-level scope at none:5
caused by [exception 1]
/Users/tkoolen/.julia/packages/SpecialFunctions/fvheQ/deps/usr/lib/libopenspecfun.1.3.dylib cannot be opened, Please re-run Pkg.build("SpecialFunctions"), and restart Julia.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] check_deps() at /Users/tkoolen/.julia/packages/SpecialFunctions/fvheQ/deps/deps.jl:20
 [3] __init__() at /Users/tkoolen/.julia/packages/SpecialFunctions/fvheQ/src/SpecialFunctions.jl:12
 [4] _include_from_serialized(::String, ::Array{Any,1}) at ./loading.jl:685
 [5] _require_search_from_serialized(::Base.PkgId, ::String) at ./loading.jl:765
 [6] _require(::Base.PkgId) at ./loading.jl:990
 [7] require(::Base.PkgId) at ./loading.jl:911
 [8] require(::Module, ::Symbol) at ./loading.jl:906
 [9] include at ./boot.jl:328 [inlined]
 [10] include_relative(::Module, ::String) at ./loading.jl:1094
 [11] include(::Module, ::String) at ./Base.jl:31
 [12] include(::String) at ./client.jl:431
 [13] top-level scope at none:5
ERROR: Package StaticArrays errored during testing
```

which is https://github.com/JuliaMath/SpecialFunctions.jl/issues/153. SpecialFunctions doesn't actually seem to be used in the tests anyway so I'll remove it as a dependency.

**Comment by tkoolen** [comment]
SpecialFunctions was added as a test dependency in https://github.com/JuliaArrays/StaticArrays.jl/pull/433, but the FixedSizeArrays compatibility layer has since been removed.

**Comment by KristofferC** [comment]
Has anyone tried this on the 1.2 backport branch?

**Comment by tkoolen** [comment]
Just tried the latest StaticArrays release on the `backports-release-1.2` branch on Linux. Unfortunately it has the same issue.

**Comment by tkoolen** [comment]
Opened https://github.com/JuliaLang/julia/issues/31899.

**Comment by tkoolen** [comment]
Should be fixed in https://github.com/JuliaLang/julia/pull/31960; hopefully nightly will turn green again soon.

**Pull request merged**
