### PR TITLE
Export StaticArraysCore (fixes #1061)

### LINKED ISSUE #1061: reading back SVector with BSON.jl fails with StaticArraysCore not defined
A copy of https://github.com/JuliaIO/BSON.jl/issues/112, [discussion](https://discourse.julialang.org/t/staticarrays-1-5-staticarrayscore-and-bson-jl/84473) suggests it could be fixed in this package:

MWE (in a clean temporary environment):
```julia
(jl_QADwAF) pkg> st
Status `/tmp/jl_QADwAF/Project.toml`
  [fbb218c0] BSON v0.3.5
  [90137ffa] StaticArrays v1.5.1

julia> VERSION
v"1.8.0-rc3"

julia> using BSON, StaticArrays

julia> d = Dict(["foo" => SVector(1.0, 2.0, 3.0)])
Dict{String, SVector{3, Float64}} with 1 entry:
  "foo" => [1.0, 2.0, 3.0]

julia> fn = tempname()
"/tmp/jl_OejeNE7YRG"

julia> BSON.bson(fn, d)

julia> BSON.load(fn)                   # fails
ERROR: UndefVarError: StaticArraysCore not defined
Stacktrace:
  [1] (::BSON.var"#31#32")(m::Module, f::String)
    @ BSON ~/.julia/packages/BSON/rOaki/src/extensions.jl:21
  [2] BottomRF
    @ ./reduce.jl:81 [inlined]
  [3] _foldl_impl(op::Base.BottomRF{BSON.var"#31#32"}, init::Module, itr::Vector{Any})
    @ Base ./reduce.jl:58
  [4] foldl_impl
    @ ./reduce.jl:48 [inlined]
  [5] mapfoldl_impl
    @ ./reduce.jl:44 [inlined]
  [6] _mapreduce_dim
    @ ./reducedim.jl:362 [inlined]
  [7] #mapreduce#765
    @ ./reducedim.jl:357 [inlined]
  [8] #reduce#767
    @ ./reducedim.jl:406 [inlined]
  [9] resolve(fs::Vector{Any}, init::Module)
    @ BSON ~/.julia/packages/BSON/rOaki/src/extensions.jl:21
 [10] (::BSON.var"#35#36")(d::Dict{Symbol, Any}, init::Module)
    @ BSON ~/.julia/packages/BSON/rOaki/src/extensions.jl:64
 [11] _raise_recursive(d::Dict{Symbol, Any}, cache::IdDict{Any, Any}, init::Module)
    @ BSON ~/.julia/packages/BSON/rOaki/src/read.jl:80
 [12] raise_recursive(d::Dict{Symbol, Any}, cache::IdDict{Any, Any}, init::Module)
    @ BSON ~/.julia/packages/BSON/rOaki/src/read.jl:93
 [13] (::BSON.var"#23#24"{IdDict{Any, Any}, Module})(x::Dict{Symbol, Any})
    @ BSON ~/.julia/packages/BSON/rOaki/src/read.jl:98
 [14] applychildren!(f::BSON.var"#23#24"{IdDict{Any, Any}, Module}, x::Vector{Any})
    @ BSON ~/.julia/packages/BSON/rOaki/src/BSON.jl:26
 [15] raise_recursive
    @ ~/.julia/packages/BSON/rOaki/src/read.jl:98 [inlined]
 [16] (::BSON.var"#17#20"{IdDict{Any, Any}, Module})(x::Vector{Any})
    @ BSON ~/.julia/packages/BSON/rOaki/src/read.jl:80
 [17] applychildren!(f::BSON.var"#17#20"{IdDict{Any, Any}, Module}, x::Dict{Symbol, Any})
    @ BSON ~/.julia/packages/BSON/rOaki/src/BSON.jl:19
 [18] _raise_recursive(d::Dict{Symbol, Any}, cache::IdDict{Any, Any}, init::Module)
    @ BSON ~/.julia/packages/BSON/rOaki/src/read.jl:80
 [19] raise_recursive(d::Dict{Symbol, Any}, cache::IdDict{Any, Any}, init::Module)
    @ BSON ~/.julia/packages/BSON/rOaki/src/read.jl:93
 [20] (::BSON.var"#49#50")(d::Dict{Symbol, Any}, cache::IdDict{Any, Any}, init::Module)
    @ BSON ~/.julia/packages/BSON/rOaki/src/extensions.jl:167
 [21] raise_recursive(d::Dict{Symbol, Any}, cache::IdDict{Any, Any}, init::Module)
    @ BSON ~/.julia/packages/BSON/rOaki/src/read.jl:92
 [22] raise_recursive
    @ ~/.julia/packages/BSON/rOaki/src/read.jl:103 [inlined]
 [23] load (repeats 2 times)
    @ ~/.julia/packages/BSON/rOaki/src/read.jl:108 [inlined]
 [24] top-level scope
    @ REPL[9]:1
```

### PR DESCRIPTION
**Pull request by mateuszbaran**
Seems to fix issue #1061.

### CODE REVIEW

**Review by tpapp — APPROVED** [review]
This fixes the issue when I test locally.

**Comment by tpapp** [comment]
I don't know if you want to test for BSON read/write in this package, but something like

```julia
import BSON
@testset "test BSON roundtrip" begin
    d = Dict(["foo" => SVector(1.0, 2.0, 3.0)])
    fn = tempname()
    BSON.bson(fn, d)
    @test BSON.load(fn) == d
end
``` 

should do it (and of course adding BSON to test dependencies).

**Comment by mateuszbaran** [comment]
Thanks for the test code but I think this is an issue that is very unlikely to happen again.

**Review by fredrikekre — APPROVED** [review]
Seems fine, but I still think this is a general issue that should be fixed in BSON. Why doesn't it store the root module of the type? (JLD2 doesn't have the same problem for example.)

**Pull request merged**
