### PR TITLE
Speedier AbstractArray conversion

### PR DESCRIPTION
**Pull request by andyferris**
This needs to test (tests don't finish on my Windows machine...)

### CODE REVIEW

**Comment by c42f** [comment]
Looks good to me (Other than the fact that there's yet one more generated function :-P )

**Comment by andyferris** [comment]
> Other than the fact that there's yet one more generated function 

Right! Oh well.

**Comment by andyferris** [comment]
Tests on my linux machine don't terminate either. Needs investigation

**Comment by andyferris** [comment]
So there might be an issue with compilation, see JuliaLang/julia#18794.

For now I've worked around this by renaming some variable names to avoid rebinding. Should be good to go, if tests pass.

**Pull request merged**
