### PR TITLE
Fix Array{T}(uninitialized,...) deprecations

### PR DESCRIPTION
**Pull request by pablosanjose**
With `@compat` decorations.

### CODE REVIEW

**Comment by fredrikekre** [comment]
There shouldn't be a need for `@compat`. But you need `Compat 0.39` in REQUIRE

**Comment by pablosanjose** [comment]
Oh! So how does it go then? You just REQUIRE Compat and use the master branch syntax, and it will just work in all versions?

That's cool!

**Comment by pablosanjose** [comment]
Just to be clear, one still needs to do `using Compat`, yes?

**Comment by fredrikekre** [comment]
Yes https://github.com/JuliaArrays/StaticArrays.jl/blob/bb5102170dae514e440c1db5f22ba6e6e2bfc59a/src/StaticArrays.jl#L19 but you might have to add it to the tests too.

**Comment by fredrikekre** [comment]
Actually, it was already there https://github.com/JuliaArrays/StaticArrays.jl/blob/3801f1742bfddec19f1331e5153bae9d08a522fe/test/testutil.jl#L2

**Pull request merged**
