### PR TITLE
Test run CI without coverage

### PR DESCRIPTION
**Pull request by fredrikekre**
Just testing this out, it should be significantly faster (see e.g. https://github.com/julia-actions/julia-runtest/pull/19#issuecomment-708345663). I think it should be sufficient to produce and submit coverage from one or two workers, I don't think there is any OS specific code-paths in StaticArrays for example.

### CODE REVIEW

**Comment by mateuszbaran** [comment]
Why does this PR have coverage checks but other recent PRs don't?

**Comment by fredrikekre** [comment]
Doesn't seem seem as bad on CI as I see locally (3+ times overhead):
```
│ Row │ os      │ version  │ overhead │
│     │ Symbol  │ Version… │ Float64  │
├─────┼─────────┼──────────┼──────────┤
│ 1   │ linux   │ v"1.0.0" │ 1.08609  │
│ 2   │ linux   │ v"1.1.0" │ 1.23864  │
│ 3   │ linux   │ v"1.2.0" │ 1.62651  │
│ 4   │ linux   │ v"1.3.0" │ 1.88571  │
│ 5   │ linux   │ v"1.4.0" │ 2.19565  │
│ 6   │ linux   │ v"1.6.0" │ 1.60976  │
│ 7   │ macOS   │ v"1.0.0" │ 0.957143 │
│ 8   │ macOS   │ v"1.4.0" │ 2.04545  │
│ 9   │ macOS   │ v"1.6.0" │ 1.42857  │
│ 10  │ windows │ v"1.0.0" │ 1.2963   │
│ 11  │ windows │ v"1.4.0" │ 1.96226  │
│ 12  │ windows │ v"1.6.0" │ 1.69767  │

│ Row │ os      │ overhead │
│     │ Symbol  │ Float64  │
├─────┼─────────┼──────────┤
│ 1   │ linux   │ 1.60706  │
│ 2   │ macOS   │ 1.47706  │
│ 3   │ windows │ 1.65208  │

│ Row │ version  │ overhead │
│     │ Version… │ Float64  │
├─────┼──────────┼──────────┤
│ 1   │ v"1.0.0" │ 1.11318  │
│ 2   │ v"1.1.0" │ 1.23864  │
│ 3   │ v"1.2.0" │ 1.62651  │
│ 4   │ v"1.3.0" │ 1.88571  │
│ 5   │ v"1.4.0" │ 2.06779  │
│ 6   │ v"1.6.0" │ 1.57867  │
```

**Comment by KristofferC** [comment]
Is CI really running on all versions except the latest released one (the most important)? :P

**Comment by c42f** [comment]
> Is CI really running on all versions except the latest released one (the most important)? :P

Apparently :facepalm:

**Pull request closed without merging**
