### PR TITLE
Implement promote_rule for StaticArray to mirror Base.Array

### LINKED ISSUE #176: Promotion rules should follow Vector
The following is inconsistent:
```julia
julia> promote_type(SVector{2,Float64},SVector{2,Complex128})
StaticArrays.SArray{Tuple{2},T,1,2} where T

julia> promote_type(Vector{Float64},Vector{Complex128})
Array{Complex{Float64},1}
```

### PR DESCRIPTION
**Pull request by c42f**
Fixes #176

### CODE REVIEW

**Comment by c42f** [comment]
I don't think `Base` does anything special with this.  The `promote_rule` declaration is specific to `Array`, and doesn't work between `Array` and `UnitRange`, for instance.

The left hand side rule is consistent with the other places where we face similar problems.  `map`, for instance.

**Comment by andyferris** [comment]
> The promote_rule declaration is specific to Array, and doesn't work between Array and UnitRange, for instance.

OK, in that case I'm changing my mind - let's implement this only for `SArray`, `MArray`, and `SizedArray` (individually).

We shouldn't simply "guess" what combinations of different array types are. Consider `[RotX(1.0), ones(SMatrix{3,3})]` - promoting both to a rotation would be a real problem! (The second isn't even unitary/orthogonal).

OTOH `map` goes through `similar` / `similar_type` which is a little bit safer since they can be set to a more "generic" container, e.g. `similar_type` for rotations are `SMatrix{3,3}`.

**Comment by c42f** [comment]
Ok, I've changed this around as suggested.  Not quite happy about the duplication, but let's go with it for now.

As part of implementing this for `SizedArray`, I found a whole heap of brokenness, so I fixed that as well and added various tests.

**Comment by c42f** [comment]
By the way, you may find the SizedArray changes easier to review by looking at the second commit in isolation.

**Pull request merged**
