### PR TITLE
Fix views with static boolean vector indexing

### LINKED ISSUE #1024: Cannot dot assign when bool indexing leads to array of smaller size
I think the example below is quite clear, but please help me with the title of this issue if it is not clear.

```julia
julia> a = [1,2,3]
3-element Vector{Int64}:
 1
 2
 3

julia> a[a .< 0] .= 0
0-element view(::Vector{Int64}, Int64[]) with eltype Int64

julia> using StaticArrays

julia> b = MVector{3}(1,2,3)
3-element MVector{3, Int64} with indices SOneTo(3):
 1
 2
 3

julia> b[b .< 0] .= 0
ERROR: DimensionMismatch("Dimensions (0,) don't match static size Tuple{3}")
Stacktrace:
 [1] SizedArray
   @ ~/.julia/packages/StaticArrays/58yy1/src/SizedArray.jl:22 [inlined]
 [2] SizedArray
   @ ~/.julia/packages/StaticArrays/58yy1/src/SizedArray.jl:46 [inlined]
 [3] view(a::MVector{3, Int64}, indices::MVector{3, Bool})
   @ StaticArrays ~/.julia/packages/StaticArrays/58yy1/src/MArray.jl:136
 [4] maybeview
   @ ./views.jl:146 [inlined]
 [5] dotview(::MVector{3, Int64}, ::MVector{3, Bool})
   @ Base.Broadcast ./broadcast.jl:1200
 [6] top-level scope
   @ REPL[8]:1

julia> b[b .> 1] .= 0
ERROR: DimensionMismatch("Dimensions (2,) don't match static size Tuple{3}")
Stacktrace:
 [1] SizedArray
   @ ~/.julia/packages/StaticArrays/58yy1/src/SizedArray.jl:22 [inlined]
 [2] SizedArray
   @ ~/.julia/packages/StaticArrays/58yy1/src/SizedArray.jl:46 [inlined]
 [3] view(a::MVector{3, Int64}, indices::MVector{3, Bool})
   @ StaticArrays ~/.julia/packages/StaticArrays/58yy1/src/MArray.jl:136
 [4] maybeview
   @ ./views.jl:146 [inlined]
 [5] dotview(::MVector{3, Int64}, ::MVector{3, Bool})
   @ Base.Broadcast ./broadcast.jl:1200
 [6] top-level scope
   @ REPL[15]:1

julia> b[b .> 0] .= 0
3-element SizedVector{3, Int64, SubArray{Int64, 1, MVector{3, Int64}, Tuple{Vector{Int64}}, false}} with indices SOneTo(3):
 0
 0
 0

julia> b
3-element MVector{3, Int64} with indices SOneTo(3):
 0
 0
 0
```

### PR DESCRIPTION
**Pull request by mateuszbaran**
Should fix #1024 .

### CODE REVIEW

**Comment by mateuszbaran** [comment]
Bump -- tests pass now without issues.

**Comment by hyrodium** [comment]
Oh, the type-instability is resolved on Julia `v1.9.0-DEV` :tada:

```julia
julia> using StaticArrays

julia> m = @MMatrix rand(3,3)
3×3 MMatrix{3, 3, Float64, 9} with indices SOneTo(3)×SOneTo(3):
 0.888748  0.322738  0.0851149
 0.674213  0.434504  0.483908
 0.632602  0.502047  0.142718

julia> view(m,:,SVector(true,false,false))
3×1 view(::MMatrix{3, 3, Float64, 9}, :, [1]) with eltype Float64 with indices SOneTo(3)×Base.OneTo(1):
 0.8887478158799568
 0.6742127481147921
 0.6326021473295187

julia> @code_warntype view(m,:,SVector(true,false,false))
MethodInstance for view(::MMatrix{3, 3, Float64, 9}, ::Colon, ::SVector{3, Bool})
  from view(a::MArray{S}, indices::Union{Colon, Integer, Base.Slice, SOneTo, StaticVector}...) where S in StaticArrays at /home/hyrodium/.julia/dev/StaticArrays/src/MArray.jl:109
Static Parameters
  S = Tuple{3, 3}
Arguments
  #self#::Core.Const(view)
  a::MMatrix{3, 3, Float64, 9}
  indices::Tuple{Colon, SVector{3, Bool}}
Locals
  #38::StaticArrays.var"#38#39"
  new_size::Union{}
  view_from_invoke::SubArray{Float64, 2, MMatrix{3, 3, Float64, 9}, Tuple{Base.Slice{SOneTo{3}}, Vector{Int64}}, false}
Body::SubArray{Float64, 2, MMatrix{3, 3, Float64, 9}, Tuple{Base.Slice{SOneTo{3}}, Vector{Int64}}, false}
1 ─       Core.NewvarNode(:(new_size))
│   %2  = Core.tuple(StaticArrays.Tuple, StaticArrays.AbstractArray)::Core.Const((Tuple, AbstractArray))
│   %3  = StaticArrays.typeof(indices)::Core.Const(Tuple{Colon, SVector{3, Bool}})
│   %4  = Base.getproperty(%3, :parameters)::Core.Const(svec(Colon, SVector{3, Bool}))
│   %5  = Core._apply_iterate(Base.iterate, Core.apply_type, %2, %4)::Core.Const(Tuple{AbstractArray, Colon, SVector{3, Bool}})
│   %6  = Core.tuple(StaticArrays.view, %5, a)::Core.PartialStruct(Tuple{typeof(view), DataType, MMatrix{3, 3, Float64, 9}}, Any[typeof(view), Core.Const(Tuple{AbstractArray, Colon, SVector{3, Bool}}), MMatrix{3, 3, Float64, 9}])
│         (view_from_invoke = Core._apply_iterate(Base.iterate, StaticArrays.invoke, %6, indices))
│         (#38 = %new(StaticArrays.:(var"#38#39")))
│   %9  = #38::Core.Const(StaticArrays.var"#38#39"())
│   %10 = StaticArrays.any(%9, indices)::Core.Const(true)
└──       goto #3 if not %10
2 ─       return view_from_invoke::Core.PartialStruct(SubArray{Float64, 2, MMatrix{3, 3, Float64, 9}, Tuple{Base.Slice{SOneTo{3}}, Vector{Int64}}, false}, Any[MMatrix{3, 3, Float64, 9}, Tuple{Base.Slice{SOneTo{3}}, Vector{Int64}}, Core.Const(0), Core.Const(0)])
3 ─       Core.Const(:(Core.tuple($(Expr(:static_parameter, 1)))))
│         Core.Const(:(new_size = Core._apply_iterate(Base.iterate, StaticArrays.new_out_size, %13, indices)))
│         Core.Const(:(Core.apply_type(StaticArrays.SizedArray, new_size)))
│         Core.Const(:((%15)(view_from_invoke)))
└──       Core.Const(:(return %16))


julia> versioninfo()
Julia Version 1.9.0-DEV.575
Commit f9aa28f215* (2022-05-13 18:51 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: 16 × AMD Ryzen 7 2700X Eight-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, znver1)
  Threads: 1 on 16 virtual cores
```

But v1.8.0-rc1 still has the instability...

**Comment by mateuszbaran** [comment]
I will check if I can make this type stable on 1.8. Constant propagation should be able to handle this.

**Comment by mateuszbaran** [comment]
OK, now it should be type stable.

**Review by hyrodium — APPROVED** [review]
LGTM!

**Pull request merged**
