### PR TITLE
Update convert.jl

### PR DESCRIPTION
**Pull request by githubtomtom**
supports promote() to SArray

### CODE REVIEW

**Comment by andyferris** [comment]
OK, this is pretty interesting - what is the desired behavior here? That operations like `SVector(1,2,3) + [1,2,3]` returns an `SVector`? Or manual usage of `promote`?

I note that `promote` was designed for `Number` and operations such as `*` can invoke automatically `promote` - while the definitions here might not make great sense for that case. Also, should the `length` be checked to be compatible, or the `size`, or the `axes` (remembering we are coming from `AbstractArray`)?

**Comment by githubtomtom** [comment]
actually I was try to do  SVector(1,2,3) .+ [1,2,3] (broadcasting) returning a SVector. Unfortunately overriding promote_rule() seems not able to achieve that automatically. I’m not familiar with broadcasting interface at the moment, would try to extend that piece later.

By the way, now we can manually use promote() which is nice I think.

**Comment by c42f** [comment]
> actually I was try to do  SVector(1,2,3) .+ [1,2,3] (broadcasting) returning a SVector

Oh right! great to know thanks.

In that case I suggest we fix broadcasting rather than messing with `promote` which is generally for use with scalars.  Unfortunately it may not be simple; the broadcasting machinery is already quite complex.

**Comment by c42f** [comment]
I've created #744 to track fixing broadcast as I think that's the correct way to fix your underlying issue.

**Pull request closed without merging**
