### PR TITLE
Make `vec` just return the argument for `MVector` and `SizedVector`.

### PR DESCRIPTION
**Pull request by mateuszbaran**
This should fix part of the problem reported in #981 .

### CODE REVIEW

**Comment by ufechner7** [comment]
I don't think that the failure on macOS-latest is related to this commit... So how to proceed?

**Comment by mateuszbaran** [comment]
That looks like a random failure. Now I'm going to wait for someone to review this PR.

**Comment by mateuszbaran** [comment]
@c42f could you check this PR? It's a small bugfix that would be nice to have.

**Comment by thchr** [comment]
This seems like a correct fix to me.

**Review by thchr — APPROVED** [review]

**Pull request merged**
