### PR TITLE
Release 0.11.1 backports (do not merge)

### PR DESCRIPTION
**Pull request by c42f**
This is a PR to run CI for a quick backported bugfix release as requested by @andreasnoack in #671. I've added that patch plus a few other extremely simple seemingly low risk fixes. We're overdue for a release 0.12.0 containing several features and a few deprecations but that will have to wait a little longer.

(Perhaps there's a better way to run CI across the various platforms?)

### CODE REVIEW

**Comment by c42f** [comment]
@andreasnoack if this passes CI, feel free to create a new release 0.11.1 from this branch using JuliaRegistrator (I may not have time to do so tomorrow).

**Comment by c42f** [comment]
@JuliaRegistrator register branch=release-0.11

**Comment by fredrikekre** [comment]
> Perhaps there's a better way to run CI across the various platforms?

Add `/^release-.*$/` to this list: https://github.com/JuliaArrays/StaticArrays.jl/blob/d1c6288290e8dad29a2376ef3eb4dad89c1bf02d/.travis.yml#L17-L19

**Comment by c42f** [comment]
> Add `/^release-.*$/` to this list

Thanks! I already did this in the last commit on this branch but we should add that patch to master as well (actually your version is more precise so we should use that).

I was more looking for a place to aggregate the CI results from appveyor and travis here at github and it seemed like a PR might be the way to do that.

**Comment by c42f** [comment]
Seems to have gone through ok.

**Pull request closed without merging**
