### PR TITLE
inline sum(f::Callable, a::StaticArray)

### LINKED ISSUE #209: `sum(f, vs)` is slow
I'm on 0.6.0-rc2.0, and the master version of `StaticArrays`. It seems that `sum(::Function, ::StaticArray)` calls the generic `mapreduce` instead of the `StaticArrays` one:

```
using StaticArrays, BenchmarkTools
vs = SVector(1.0, 2.0, 3.0);

julia> @btime sum($vs);
  1.457 ns (0 allocations: 0 bytes)

julia> @btime sum(abs2, $vs);
  38.537 ns (2 allocations: 48 bytes)

julia> @btime mapreduce(abs2, +, $vs);
  1.739 ns (0 allocations: 0 bytes)

julia> @btime sumabs2($vs);
  1.746 ns (0 allocations: 0 bytes)
```

### PR DESCRIPTION
**Pull request by fredrikekre**
Since I derped in #209 i fixed it :) 
fix #209

### CODE REVIEW

**Comment by c42f** [comment]
> Should this work for length zero vectors?

Might be nice. I assume that's a side comment about `mapreduce` rather than something particularly relevant to this PR?

**Comment by andyferris** [comment]
No it's specific to `sum` (`v0= zero(T)`) and `prod` (`v0 = one(T)`). In general, an appropriate `v0` cannot be chosen for `mapreduce`.

**Comment by fredrikekre** [comment]
To be clear, this only inlines the corresponding method from base (https://github.com/JuliaLang/julia/blob/ef9ab602b0307afb9fa21f2323e2abf4b244ad41/base/reduce.jl#L347), so this does not change any behaviour.

**Comment by andyferris** [comment]
Yes, thanks @fredrikekre. These comments are more for the future (sorry my "no" above was ambiguous - was referring to Chris's comment on `mapreduce` specifically, not this PR).

**Comment by c42f** [comment]
Seems relevant here, as we have in base:

```julia
julia> sum(identity, Int[])
0
```

**Comment by c42f** [comment]
Hmm, and yet...

```julia
julia> sum(x->x/2, Int[])
ERROR: ArgumentError: reducing over an empty collection is not allowed
Stacktrace:
 [1] _mapreduce(::##1#2, ::Base.#+, ::IndexLinear, ::Array{Int64,1}) at ./reduce.jl:265
 [2] sum(::Function, ::Array{Int64,1}) at ./reduce.jl:347
```

Which seems rather odd until I looked at the Base implementation of `mapreduce`, where instead of using inference there are a bunch of special cases hardcoded for specific functions (including `identity`).

So I'm just going to merge this :-)

**Pull request merged**
