### PR TITLE
Last test for deque?

### PR DESCRIPTION
**Pull request by kshyatt**

### CODE REVIEW

**Comment by kshyatt** [comment]
Hmm, this doesn't seem to be testing that line, I wonder why.

**Comment by mschauer** [comment]
The method
```julia
setindex(a::StaticArray, x, inds::Int...) = setindex(a, x, sub2ind(size(typeof(a)), inds...))
```
in https://github.com/JuliaArrays/StaticArrays.jl/blob/master/src/deque.jl#L88 is an immutable version of `setindex!` and needs to be called specifally.

**Comment by mschauer** [comment]
@kshyatt I think this is not what you wanted to do.

**Comment by kshyatt** [comment]
Yeah, I think you're right. Haven't had time to go back and fix it if
someone else wants to.

**Comment by mschauer** [comment]
Nah - if at some point coverage is 99.9%, we *then* now where to look...

**Pull request merged**
