### PR TITLE
Fix definition of prod()

### PR DESCRIPTION
**Pull request by umgrmxsvaf**
Seems to just be a typo. :)

This is my first pull request, so hopefully I did it correctly.

### CODE REVIEW

**Comment by KristofferC** [comment]
Generally when you fix a bug like this it is always an extra bonus if there is an accompanying test such that the bug doesn't creep back up and to make sure that the fix actually works :).

**Comment by umgrmxsvaf** [comment]
Hmmm, I'll try to figure out such tests go.

**Comment by umgrmxsvaf** [comment]
Sorry about that. ^_^; Thanks for the advice.

**Comment by c42f** [comment]
Great, thanks for the patch, and the tests :-)

**Pull request merged**
