### PR TITLE
Run CI on latest released 1.x version

### PR DESCRIPTION
**Pull request by thchr**
I noticed that CI wasn't running on 1.6, which I figured would be a good idea, even if it increases the run-time.

With this PR, it still doesn't run on 1.5, and won't run on 1.6 after 1.7 is released (then it'll run on 1.7) - but it seems better than not to run at all, and doesn't increase CI time very much compared to adding everything.

### CODE REVIEW

**Comment by thchr** [comment]
I added some fixes to tests, so that this should now ideally also pass the test-suite on v1.6.

All test failures turned out to have been noted in the issue tracker already.

Closes #912, #924, #925

**Comment by thchr** [comment]
Huh, seems this didn't quite fix #925. Not sure if this isn't really a bug in Julia instead. Specifically, if we define:
```jl
julia> using StaticArrays, Test, LinearAlgebra
julia> m_sing2 = @SMatrix [1 1; 1 0; 0 1];
julia> svd_full_false(A) = svd(A, full=false);
```
and consult `@code_warntype`, everything is fine:
```jl
julia> @code_warntype svd_full_false(m_sing2)
Variables
  #self#::Core.Const(svd_full_false)
  A::SMatrix{3, 2, Int64, 6}

Body::StaticArrays.SVD{Float64, SMatrix{3, 2, Float64, 6}, SVector{2, Float64}, SMatrix{2, 2, Float64, 4}}
1 ─ %1 = (:full,)::Core.Const((:full,))
│   %2 = Core.apply_type(Core.NamedTuple, %1)::Core.Const(NamedTuple{(:full,), T} where T<:Tuple)
│   %3 = Core.tuple(false)::Core.Const((false,))
│   %4 = (%2)(%3)::Core.Const((full = false,))
│   %5 = Core.kwfunc(Main.svd)::Core.Const(LinearAlgebra.var"#svd##kw"())
│   %6 = (%5)(%4, Main.svd, A)::StaticArrays.SVD{Float64, SMatrix{3, 2, Float64, 6}, SVector{2, Float64}, SMatrix{2, 2, Float64, 4}}
└──      return %6
```
But `@inferred` insists this isn't inferred (contrary to `@code_warntype`):
```jl
julia> @inferred svd_full_false(m_sing2)
ERROR: return type StaticArrays.SVD{Float64, SMatrix{3, 2, Float64, 6}, SVector{2, Float64}, SMatrix{2, 2, Float64, 4}} does not match inferred return type Union{StaticArrays.SVD{Float64, SMatrix{3, 2, Float64, 6}, SVector{2, Float64}, SMatrix{2, 2, Float64, 4}}, StaticArrays.SVD{Float64, SMatrix{3, 3, Float64, 9}, SVector{2, Float64}, SMatrix{2, 2, Float64, 4}}}
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] top-level scope
   @ REPL[19]:1
```


Pretty sure I even had one REPL session where `@inferred` seemed to be working, but then it didn't in another session.

**Comment by thchr** [comment]
Okay; I just disabled the `svd(A, full=false)` kwarg constant-propagation test on v1.6 and later: for whatever reason, it just doesn't seem to work (even though, puzzlingly, small toy-examples with constant propagation of keyword arguments certainly do work).

**Comment by thchr** [comment]
This now also changes a few `@test_broken` in `test/abstractarrays.lj` to `@test` on the nightly version of Julia (they got fixed by https://github.com/JuliaLang/julia/pull/40831 apparently).

That's basically unrelated to this PR - but I just wanted to see if I could get the nightly CI passing (sadly, there were more issues down the line - I'm going to leave them for now).

**Comment by KristofferC** [comment]
Great, thanks. @mateuszbaran can this be merged? It would be nice to have StaticArrays test pass on latest release or otherwise regressions won't be noticed by PkgEval for upcoming releases (e.g. 1.7).

**Comment by mateuszbaran** [comment]
Yes, right, I'll merge this. I think this doesn't require a new release because only tests are changed.

**Comment by KristofferC** [comment]
True but unless it gets a release PkgEval won't pick it up. However, there might be other things that will require a release soon anyway, like the `reshape` thing.

**Comment by mateuszbaran** [comment]
Yes, I think both that `reshape` thing and #931 require urgent fixing. I'm a bit busy today but I should be able work on this tomorrow if no one else does.

**Comment by thchr** [comment]
#932 should fix the `qr` ambiguity problem (as well as the `lu` ambiguities that remained on Nightly testing on this PR).

**Pull request merged**
