### PR TITLE
discussing broadcast performance issues for immutable StaticArrays in the docs

### PR DESCRIPTION
**Pull request by jlchan**
I found out from a more experienced dev about broadcasting slowdowns using immutable StaticArrrays https://github.com/JuliaArrays/StaticArrays.jl/issues/560, https://github.com/SciML/DifferentialEquations.jl/issues/436. 
```julia
julia> x = SVector{4}(ones(4)); y = SVector{4}(ones(4)); a,b = randn(2)
julia> @btime @. $a*$x+$b*$y;  
  1.712 ns (0 allocations: 0 bytes)
julia> @btime $a*$x+$b*$y;
  0.045 ns (0 allocations: 0 bytes)
```
I couldn't identify it on my own since it's not a large performance hit and doesn't incur allocations; however fixing it resulted in 4x speedup of my code. Since this is buried in the issues, I thought it might be useful for other newer users to add this to the documentation.

The changes are:
1. split the section "Working with mutable and immutable arrays" into sections "Manipulating mutable and immutable arrays" and "Performance tips specific to mutable or immutable arrays"
2. added an example showing the slowdown for immutable StaticArrays 
3. linked some relevant open issues related to broadcast.

Please let me know if you have any comments or suggestions, and I'd be happy to incorporate them!

### CODE REVIEW

**Comment by jlchan** [comment]
I would also like to reorganize the docs so that there is more information viewable from the sidebar (have different sections in the sidebar instead of just API and docstrings links) but I can put that in another PR.

**Comment by mateuszbaran** [comment]
Some performance problems related to broadcasting are quite bad but this difference looks like an issue with BenchmarkTools. Both variants give me almost the same native code on my platform:
```julia
julia> f(a, x, b, y) = @. a*x+b*y
f (generic function with 1 method)

julia> @code_native f(a, x, b, y)
	.text
; ┌ @ REPL[6]:1 within `f'
; │┌ @ broadcast.jl:883 within `materialize'
; ││┌ @ broadcast.jl:26 within `copy'
; │││┌ @ broadcast.jl:99 within `_broadcast'
; ││││┌ @ broadcast.jl:125 within `macro expansion'
; │││││┌ @ broadcast.jl:314 within `#2'
; ││││││┌ @ broadcast.jl:367 within `#8' @ broadcast.jl:368
; │││││││┌ @ float.jl:332 within `*'
	vbroadcastsd	%xmm1, %ymm1
; ││││││└└
; ││││││┌ @ broadcast.jl:368 within `#8'
; │││││││┌ @ float.jl:332 within `*'
	vbroadcastsd	%xmm0, %ymm0
	movq	%rdi, %rax
; ││││││└└
; ││││││┌ @ broadcast.jl:367 within `#8' @ broadcast.jl:368
; │││││││┌ @ float.jl:332 within `*'
	vmulpd	(%rdx), %ymm1, %ymm1
; ││││││└└
; ││││││┌ @ broadcast.jl:368 within `#8'
; │││││││┌ @ float.jl:332 within `*'
	vmulpd	(%rsi), %ymm0, %ymm0
; ││││││└└
; ││││││┌ @ float.jl:326 within `+'
	vaddpd	%ymm0, %ymm1, %ymm0
; │└└└└└└
	vmovupd	%ymm0, (%rdi)
	vzeroupper
	retq
	nopw	%cs:(%rax,%rax)
; └

julia> f2(a, x, b, y) =a*x+b*y
f2 (generic function with 1 method)

julia> @code_native f2(a, x, b, y)
	.text
; ┌ @ REPL[8]:1 within `f2'
; │┌ @ linalg.jl:20 within `*'
; ││┌ @ broadcast.jl:821 within `broadcast'
; │││┌ @ broadcast.jl:883 within `materialize'
; ││││┌ @ broadcast.jl:26 within `copy'
; │││││┌ @ broadcast.jl:99 within `_broadcast'
; ││││││┌ @ broadcast.jl:125 within `macro expansion'
; │││││││┌ @ float.jl:332 within `*'
	vbroadcastsd	%xmm0, %ymm0
	vbroadcastsd	%xmm1, %ymm1
	movq	%rdi, %rax
	vmulpd	(%rsi), %ymm0, %ymm0
	vmulpd	(%rdx), %ymm1, %ymm1
; │└└└└└└└
; │┌ @ linalg.jl:11 within `+'
; ││┌ @ mapreduce.jl:37 within `map'
; │││┌ @ mapreduce.jl:40 within `_map'
; ││││┌ @ mapreduce.jl:75 within `macro expansion'
; │││││┌ @ float.jl:326 within `+'
	vaddpd	%ymm1, %ymm0, %ymm0
; │└└└└└
	vmovupd	%ymm0, (%rdi)
	vzeroupper
	retq
	nopw	%cs:(%rax,%rax)
; └
```
`@code_typed` also looks like just a slightly different order of operations. I don't think this example illustrates issues with broadcasting performance well.

Regarding BenchmarkTools, I generally consider all results below 5ns it gives as essentially non-measurably fast. I guess your issue where removing broadcasting actually helps may be a bit more complex?

**Comment by jlchan** [comment]
Hm - that's very odd. It's not that much more complex, the line was 
```julia
val = @. (Fx * nxJ[i,e] + Fy * nyJ[i,e] - .5*(UP - UM)*sJ[i,e]) * wf[i]
```
where anything without an index was an `SVector`.

**Comment by jlchan** [comment]
My impression was that this was related to https://github.com/JuliaArrays/StaticArrays.jl/issues/797. If I time 
`a*x+y` with 3 terms instead of `a*x+b*y` then they have the same runtime. 

What version are you using? `@code_native` gives me very different results

```julia
julia> @code_native @. a*x+b*y
        .section        __TEXT,__text,regular,pure_instructions
        .build_version macos, 10, 15
        .globl  _julia_@__dot___4325            ## -- Begin function julia_@__dot___4325
        .p2align        4, 0x90
_julia_@__dot___4325:                   ## @"julia_@__dot___4325"
        .cfi_startproc
## %bb.0:                               ## %top
        pushq   %r14
        .cfi_def_cfa_offset 16
        pushq   %rbx
        .cfi_def_cfa_offset 24
        subq    $40, %rsp
        .cfi_def_cfa_offset 64
        .cfi_offset %rbx, -24
        .cfi_offset %r14, -16
        movq    %rdx, %r14
        vxorps  %xmm0, %xmm0, %xmm0
        vmovaps %xmm0, (%rsp)
        movq    $0, 16(%rsp)
        movabsq $4500749072, %rax               ## imm = 0x10C43FB10
        callq   *%rax
        movq    %rax, %rbx
        movq    $4, (%rsp)
        movq    (%rax), %rax
        movq    %rax, 8(%rsp)
        movq    %rsp, %rax
        movq    %rax, (%rbx)
        movq    %r14, 24(%rsp)
        movabsq $_j1___dot___4327, %rax
        movabsq $4658330000, %rdi               ## imm = 0x115A87990
        leaq    24(%rsp), %r14
        movq    %r14, %rsi
        movl    $1, %edx
        callq   *%rax
        movq    %rax, 16(%rsp)
        movabsq $4515667648, %rcx               ## imm = 0x10D279EC0
        movq    %rcx, 24(%rsp)
        movq    %rax, 32(%rsp)
        movabsq $_jl_f__expr, %rax
        xorl    %edi, %edi
        movq    %r14, %rsi
        movl    $2, %edx
        callq   *%rax
        movq    8(%rsp), %rcx
        movq    %rcx, (%rbx)
        addq    $40, %rsp
        popq    %rbx
        popq    %r14
        retq
        .cfi_endproc
                                        ## -- End function
.subsections_via_symbols

julia> @code_native a*x+b*y
        .section        __TEXT,__text,regular,pure_instructions
; ┌ @ broadcast.jl:411 within `+'
        pushq   %r15
        pushq   %r14
        pushq   %r13
        pushq   %r12
        pushq   %rbx
        movq    %rcx, %r14
        movq    %rdx, %r12
        movq    %rsi, %r15
        movq    %rdi, %r13
        movabsq $jl_get_ptls_states_fast, %rbx
        callq   *%rbx
; │┌ @ broadcast.jl:402 within `materialize'
; ││┌ @ broadcast.jl:141 within `similar'
; │││┌ @ stridearray.jl:40 within `StrideArray'
; ││││┌ @ stridearray.jl:23 within `undef_memory_buffer'
; │││││┌ @ stridearray.jl:5 within `MemoryBuffer'
        movabsq $jl_gc_pool_alloc, %rcx
        movq    %rax, %rdi
        movl    $1448, %esi                     ## imm = 0x5A8
        movl    $48, %edx
        callq   *%rcx
        addq    $258545024, %rbx                ## imm = 0xF691580
        movq    %rbx, -8(%rax)
; ││└└└└
; ││┌ @ broadcast.jl:376 within `materialize!'
; │││┌ @ broadcast.jl:270 within `_materialize!'
; ││││┌ @ broadcast.jl:270 within `macro expansion'
; │││││┌ @ reconstruct_loopset.jl:672 within `_avx_!'
; ││││││┌ @ reconstruct_loopset.jl:672 within `macro expansion'
; │││││││┌ @ stridedpointers.jl:169 within `_vload'
; ││││││││┌ @ memory_addr.jl:587 within `__vload'
; │││││││││┌ @ memory_addr.jl:587 within `macro expansion'
        movq    (%r12), %rcx
        vmovupd (%rcx), %ymm0
        movq    (%r14), %rcx
; │││││││└└└
; │││││││┌ @ base_defs.jl:85 within `+'
; ││││││││┌ @ binary_ops.jl:64 within `vadd'
; │││││││││┌ @ binary_ops.jl:64 within `macro expansion'
        vaddpd  (%rcx), %ymm0, %ymm0
; │││││││└└└
; │││││││┌ @ stridedpointers.jl:207 within `_vstore!'
; ││││││││┌ @ memory_addr.jl:766 within `__vstore!'
; │││││││││┌ @ memory_addr.jl:766 within `macro expansion'
        vmovupd %ymm0, (%rax)
; │└└└└└└└└└
        movq    %rax, (%r15)
        movq    %rax, (%r13)
        movq    %rax, 8(%r13)
        movq    %r13, %rax
        popq    %rbx
        popq    %r12
        popq    %r13
        popq    %r14
        popq    %r15
        vzeroupper
        retq
        nopw    %cs:(%rax,%rax)
; └
```

**Comment by andyferris** [comment]
Yes this in particular looks spurious?

```julia
julia> @btime $a*$x+$b*$y;
  0.045 ns (0 allocations: 0 bytes)
```

It kinda looks like you have a 40GHz CPU with SIMD fused-multiply-add. Or, more likely, an issue with BenchmarkTools. (as stated earlier, Julia is "too good" at optimizing things sometimes and it throws away unnecessary computation, making life difficult for writing microbenchmarks).

It's actually kinda impressive that we can do all these multiplications and additions in 1.7 nanoseconds. *Nano*. :exploding_head:

**Comment by jlchan** [comment]
Hmm, looking more closely at the benchmarks, this doesn't capture what happened. This is closer - it seems to be a broadcast inference problem.

A minimal-ish example
```julia
function foo1(a,b,c,d,x::SVector{N},y::SVector{N},z::SVector{N}) where {N}
    val = SVector{N}(zeros(N))
    for i in eachindex(a,b,c,d)
        val += (a[i]*x + b[i]*y + c[i]*(z-x-y))*d[i]
    end
end

function foo2(a,b,c,d,x::SVector{N},y::SVector{N},z::SVector{N}) where {N}
    val = SVector{N}(zeros(N))
    for i in eachindex(a,b,c,d)
        val += @. (a[i]*x + b[i]*y + c[i]*(z-x-y))*d[i]
    end
end
a,b,c,d = ntuple(_->randn(100),4)
x,y,z = ntuple(_->SVector{4}(randn(4)),3)

@btime foo1($a,$b,$c,$d,$x,$y,$z) # 109.969 ns (1 allocation: 112 bytes)
@btime foo2($a,$b,$c,$d,$x,$y,$z) # 655.100 μs (19201 allocations: 350.11 KiB)
```
Sorry for the trouble, and thanks for catching that this was a separate issue! I must have somehow missed the massive jump in allocations previously.

Since this seems like a pretty clear inference issue from the allocations, I don't think this needs to be added to the docs anymore. Thanks for looking this over!

**Comment by mateuszbaran** [comment]
> What version are you using? `@code_native` gives me very different results

I'm using Julia 1.6.1. One thing though, could you try using `@code_native` on a function that wraps a calculation instead (like I did in my example)? Sometimes it makes a big difference.

> Since this seems like a pretty clear inference issue from the allocations, I don't think this needs to be added to the docs anymore. Thanks for looking this over!

These are very specific inference issues caused by Julia not being able to simplify the `Broadcast.make_makeargs` calls. I'm genuinely surprised that such issues are not much more common.

**Comment by jlchan** [comment]
> I'm using Julia 1.6.1. One thing though, could you try using `@code_native` on a function that wraps a calculation instead (like I did in my example)? Sometimes it makes a big difference.

I get the same output from `@code_native` for both `f` and `f2` in your example. Thanks - I didn't know that would make a difference too. 

> These are very specific inference issues caused by Julia not being able to simplify the `Broadcast.make_makeargs` calls. I'm genuinely surprised that such issues are not much more common.

That's somewhat scary to hear.

**Pull request closed without merging**
