### PR TITLE
Add matrix exponential for 1x1 and 2x2, and fallback to Base

### PR DESCRIPTION
**Pull request by Godisemo**
Same as #160, but to master branch

### CODE REVIEW

**Comment by c42f** [comment]
The test errors here seem spurious.  I've restarted the build in the hope it might fix things.

**Comment by andyferris** [comment]
Needs rebasing.

**Comment by c42f** [comment]
The test failures here are my fault (see #175).  Hopefully will fix it up later tonight.

**Comment by andyferris** [comment]
Thanks @Godisemo for the contribution - appreciated :)

**Pull request merged**
