### PR TITLE
Inline `svd` to enable constant-propagation of `full`

### PR DESCRIPTION
**Pull request by jishnub**
Following the suggestion in https://github.com/JuliaLang/julia/issues/53038#issuecomment-1913939448

This should help with the `svd` regression on Julia nightly, as reported in https://github.com/JuliaLang/julia/issues/53038

### CODE REVIEW

**Review by hyrodium — COMMENTED** [review]
Could you add tests with `@inferred`?

**Comment by jishnub** [comment]
These tests already exist, and these were failing without this PR. E.g:
https://github.com/JuliaArrays/StaticArrays.jl/blob/819dbc623aa8f684e9ad7d561ed34215d7e4d160/test/svd.jl#L80-L85

**Comment by hyrodium** [comment]
Ah, sorry for overlooking that.
Test failure log: https://github.com/JuliaArrays/StaticArrays.jl/actions/runs/7654501407/job/20858625602

**Review by hyrodium — APPROVED** [review]
LGTM! :+1:

**Review by mateuszbaran — APPROVED** [review]

**Pull request merged**
