### PR TITLE
Add `reshape` methods

### LINKED ISSUE #947: Missing methods for `reshape`?
I thought this would work, and produce a SizedArray:
```julia
julia> using StaticArrays

julia> reshape(hcat([1,2,3]), axes(SA[1,2,3]))
ERROR: MethodError: no method matching reshape(::Matrix{Int64}, ::Tuple{SOneTo{3}})

julia> SizedArray{Tuple{3}}([1,2,3])  # what I expected:
3-element SizedVector{3, Int64, Vector{Int64}} with indices SOneTo(3):
 1
 2
 3
```
Context is https://github.com/FluxML/Zygote.jl/pull/1044, trying to make AD more careful about restoring the types of its inputs. Reshaping like this works for OffsetArrays, which in fact (piratically) resolves the above error:
```
julia> using OffsetArrays

julia> reshape(hcat([1,2,3]), axes(SA[1,2,3]))  # this works...
3-element OffsetArray(::Vector{Int64}, 1:3) with eltype Int64 with indices 1:3:
 1
 2
 3

julia> reshape(hcat([1,2,3]), axes(OffsetArray([1,2,3],3)))  # as a size-effect of this ...
3-element OffsetArray(::Vector{Int64}, 4:6) with eltype Int64 with indices 4:6:
 1
 2
 3

julia> reshape(hcat([1,2,3]), (4:6,))  # ... because it's piratically broad.
3-element OffsetArray(::Vector{Int64}, 4:6) with eltype Int64 with indices 4:6:
 1
 2
 3
```

### PR DESCRIPTION
**Pull request by mcabbott**
Fixes #947

But one case doesn't work, and I didn't understand why yet.

### CODE REVIEW

**Comment by mateuszbaran** [comment]
I think you have to make a special case for reshaping `AbstractVector`, similarly to `reshape(a::Vector, ::Size{S}) where {S} = SizedArray{Tuple{S...}}(a)`.

**Comment by mcabbott** [comment]
Ok, great. Somehow I assumed the Array inside would be reshaped, but I guess there is no need.

**Comment by mateuszbaran** [comment]
Yes, `SizedArray` doesn't do any reshaping of the wrapped array if there is no need to, and in general it relies on linear indexing to access the wrapped array.

**Review by mateuszbaran — APPROVED** [review]

**Comment by mateuszbaran** [comment]
OK, I'm going to merge this tomorrow. Could you bump patch version?

**Pull request merged**
