### PR TITLE
Drop Julia v0.7 support, remove deprecations

### PR DESCRIPTION
**Pull request by andyferris**
We have a solid release for Julia v0.7, which should be good enough for users needing to upgrade to v1.0. Personally, I don't feel it is valuable keeping around the old fluff.

I'm interested in getting this in for #522

### CODE REVIEW

**Comment by andyferris** [comment]
FYI, I kept the deprecations for #515 and #521, since there is no release with those.

**Comment by andyferris** [comment]
> That way people can have consistent functionality in StaticArrays-0.9 in both julia-0.7 and julia-1.0?

Consistent? The idea here was that julia-0.7 users wouldn't be able to install StaticArrays-0.9. StaticArrays-0.8 provides a consistent, upgrade layer.

Is it more that the bugs fixed in StaticArrays-0.9 will be important enough to include for users simply upgrading their Julia-0.6 code to Julia-1.0?

**Comment by c42f** [comment]
Yes, there's bugs fixed in StaticArrays-0.9; they're minor but did break my own code when upgrading from 0.6.

My point is, we loose very little by delaying the removal of these potentially helpful deprecations (and the ability to install on 0.7) by another release. And it could be rather helpful for other package maintainers.

Just a thought, no major worries if it's merged right away.

**Comment by mschauer** [comment]
Can we remove the deprecation warnings without bumping the required version? I suppose the new release will run just fine on 0.7. (I prefer my coworkers using 0.7 for the time being, that makes it easier for me to help them and for them to help themselves using stackoverflow etc.)

**Comment by c42f** [comment]
@mschauer I think that's quite reasonable. That will let users who are on 0.7 continue to get StaticArrays related bugfixes.

The only downside being that the depwarns won't be consistent with `Base` 0.7 related depwarns. But I think that's a reasonable tradeoff.

**Comment by c42f** [comment]
Partially obsoleted by #600 (though I didn't drop 0.7 support there)

**Comment by mschauer** [comment]
My earlier objection is obsolete now, in any case.

**Pull request closed without merging**
