### PR TITLE
Utilize lu for det, inv, solve, expm

### PR DESCRIPTION
**Pull request by schmrlng**
Notes:
- 14 (the threshold for dispatching to `Base` versions of functions, inherited from `lu`) may be worth canonizing somewhere instead of appearing repeatedly as a magic number.
- `solve` and `\` currently only work for square matrices on the LHS, though the same was true of the `inv(a) * b` stopgap previously in place (i.e., no functionality has been lost). Maybe `solve` should be folded into the `ldiv` family of functions in some future update.
- There's currently no size threshold for falling back to `Base` in `expm`. Compile times can get into the minutes beyond 15 x 15; I think this is a consequence of `mul!` never being dispatched to its `Base` version.

### CODE REVIEW

**Comment by tkoolen** [comment]
> Compile times can get into the minutes beyond 15 x 15

Yeah, I'm generally a little worried about the compile times for the LU code; testing the LU stuff probably takes about 80% of total test time.

**Comment by martinholters** [comment]
> Yeah, I'm generally a little worried about the compile times for the LU code;

Indeed. It was a nice exercise and it's cool that it's working, but it might not be too practical.

What I think we can do on 0.7, with the better allocation elision, is to convert the input to an `MMatrix`, have an inplace LU algorithm working on that, then return it converted to an `SMatrix`, and not suffer from any allocations.

**Comment by andyferris** [comment]
Cool! Any analysis of speed and/or accuracy?

Yes, I do agree with the comments above. If it's true that `expm` is slow for large sizes we should definitely fix that, but

> I think this is a consequence of `mul!` never being dispatched to its `Base` version.

doesn't `mul!` call BLAS directly for large matrices?

> What I think we can do on 0.7, with the better allocation elision, is to convert the input to an MMatrix, have an inplace LU algorithm working on that, then return it converted to an SMatrix, and not suffer from any allocations.

Yes - I'd really love to see proof of this working. It would be really cool and would be the "correct" way of dealing with larger structures. In fact, we could use BLAS and LAPACK a lot more - we just pass stack pointers to inputs and outputs. In the original code (way back before StaticArrays was even released) I had `MMatrix` as basically `RefValue{SMatrix}` which was kind-of neat for this kind of thing. Speculatively, I've thought rather than `similar_type` and construction, we should use `similar`, allocation elision and mutation, followed by `publish`, which is a function that says "I'm done mutating this" and would unwrap the ref and return the result. (Basically, there's no reason mutation of "immutables" should be invalid during the *construction* phase).

**Comment by schmrlng** [comment]
> Cool! Any analysis of speed and/or accuracy?

Not a particularly exhaustive study (especially in terms of accuracy), but here's a quick/dirty look:

```julia
using StaticArrays, BenchmarkTools, DataFrames, DataStructures

Nmax = 20
unary = (det, inv, expm)
binary = (\,)

data = OrderedDict{Symbol,Any}()
data[:SIZE] = vcat(([i, "", "", ""] for i in 1:Nmax)...)
data[:STAT] = [stat for sz in 1:Nmax for stat in ("compile time (s)", "StaticArrays (μs)", "Base (μs)", "max error")]

for f in unary
    f_data = Float64[]
    for N in 1:Nmax
        print("\r$((f,N))")
        SA = @SMatrix rand(N,N)
        A = Array(SA)
        push!(f_data, @elapsed f(SA))
        push!(f_data, 1e6*@belapsed $f($SA))
        push!(f_data, 1e6*@belapsed $f($A))
        push!(f_data, maximum([begin
                                   SA = @SMatrix rand(N,N)
                                   A = Array(SA)
                                   norm(f(A) - f(SA))
                               end for i in 1:1000]))
    end
    data[Symbol(f)] = f_data
end

for f in binary
    f_data = Float64[]
    for N in 1:Nmax
        print("\r$((f,N))")
        SA = @SMatrix rand(N,N)
        A = Array(SA)
        SB = @SMatrix rand(N,N)
        B = Array(SB)
        push!(f_data, @elapsed f(SA,SB))
        push!(f_data, 1e6*@belapsed $f($SA,$SB))
        push!(f_data, 1e6*@belapsed $f($A,$B))
        push!(f_data, maximum([begin
                                   SA = @SMatrix rand(N,N)
                                   A = Array(SA)
                                   SB = @SMatrix rand(N,N)
                                   B = Array(SB)
                                   norm(f(A,B) - f(SA,SB))
                               end for i in 1:1000]))
    end
    data[Symbol(f)] = f_data
end

df = DataFrame(data...)
```

| Row | SIZE | STAT              | det         | inv         | expm        | \\          |
|-----|------|-------------------|-------------|-------------|-------------|-------------|
| 1   | 1    | compile time (s)  | 0.0364483   | 0.0045792   | 0.0312345   | 0.103929    |
| 2   |      | StaticArrays (μs) | 0.001813    | 0.001813    | 0.0106907   | 0.004638    |
| 3   |      | Base (μs)         | 0.0570183   | 0.219218    | 0.785222    | 0.0876576   |
| 4   |      | max error         | 0.0         | 0.0         | 0.0         | 0.0         |
| 5   | 2    | compile time (s)  | 0.00566247  | 0.00558462  | 0.0120008   | 0.104879    |
| 6   |      | StaticArrays (μs) | 0.001813    | 0.002053    | 0.0487244   | 0.0343142   |
| 7   |      | Base (μs)         | 0.19096     | 0.553697    | 2.13967     | 1.49818     |
| 8   |      | max error         | 1.66533e-16 | 1.48144e-10 | 4.80075e-15 | 1.13687e-13 |
| 9   | 3    | compile time (s)  | 0.0859074   | 0.0501759   | 1.1237      | 0.0145437   |
| 10  |      | StaticArrays (μs) | 0.001853    | 0.00998799  | 0.150187    | 0.0606551   |
| 11  |      | Base (μs)         | 0.243269    | 0.657994    | 3.28178     | 0.9598      |
| 12  |      | max error         | 2.22045e-16 | 3.22551e-10 | 5.77749e-15 | 3.23627e-11 |
| 13  | 4    | compile time (s)  | 0.0186308   | 0.860132    | 1.12616     | 0.0228918   |
| 14  |      | StaticArrays (μs) | 0.0104394   | 0.0403582   | 0.303203    | 0.111685    |
| 15  |      | Base (μs)         | 0.298942    | 0.9067      | 4.9455      | 1.1241      |
| 16  |      | max error         | 3.05311e-16 | 3.89901e-9  | 1.06359e-14 | 2.25173e-9  |
| 17  | 5    | compile time (s)  | 2.96248     | 0.416201    | 1.59949     | 0.0422496   |
| 18  |      | StaticArrays (μs) | 0.118956    | 0.200261    | 0.519984    | 0.196676    |
| 19  |      | Base (μs)         | 0.37203     | 1.0781      | 6.06483     | 1.4858      |
| 20  |      | max error         | 1.38778e-16 | 1.04235e-8  | 2.08472e-14 | 5.66155e-9  |
| 21  | 6    | compile time (s)  | 0.611857    | 0.269671    | 2.69713     | 0.0607239   |
| 22  |      | StaticArrays (μs) | 0.202012    | 0.332716    | 0.836027    | 0.325026    |
| 23  |      | Base (μs)         | 0.446449    | 1.2233      | 7.8268      | 1.8956      |
| 24  |      | max error         | 1.11022e-16 | 4.5986e-11  | 4.25724e-14 | 1.32592e-9  |
| 25  | 7    | compile time (s)  | 0.713637    | 0.371828    | 4.42408     | 0.0960149   |
| 26  |      | StaticArrays (μs) | 0.287543    | 0.480241    | 1.2353      | 0.473852    |
| 27  |      | Base (μs)         | 0.535745    | 1.3796      | 6.91967     | 1.62089     |
| 28  |      | max error         | 2.22045e-16 | 6.79111e-9  | 1.20773e-13 | 7.26078e-9  |
| 29  | 8    | compile time (s)  | 0.798045    | 0.511637    | 7.6505      | 0.146561    |
| 30  |      | StaticArrays (μs) | 0.3978      | 0.671327    | 1.7402      | 0.68227     |
| 31  |      | Base (μs)         | 0.627035    | 1.576       | 7.81833     | 2.95313     |
| 32  |      | max error         | 1.66533e-16 | 2.4866e-9   | 2.62318e-13 | 8.25686e-9  |
| 33  | 9    | compile time (s)  | 0.945135    | 0.685985    | 3.4902      | 0.223793    |
| 34  |      | StaticArrays (μs) | 0.582757    | 0.982571    | 3.11212     | 0.950913    |
| 35  |      | Base (μs)         | 0.748684    | 1.8966      | 9.979       | 3.38512     |
| 36  |      | max error         | 3.33067e-16 | 4.72522e-6  | 3.46584e-13 | 1.20361e-8  |
| 37  | 10   | compile time (s)  | 1.11504     | 0.941347    | 4.35427     | 0.275104    |
| 38  |      | StaticArrays (μs) | 0.792808    | 1.3014      | 4.13357     | 1.4347      |
| 39  |      | Base (μs)         | 3.27238     | 4.10071     | 13.395      | 5.46533     |
| 40  |      | max error         | 1.94289e-16 | 4.5242e-9   | 2.13996e-13 | 2.2899e-10  |
| 41  | 11   | compile time (s)  | 1.35308     | 1.24002     | 5.47648     | 0.406524    |
| 42  |      | StaticArrays (μs) | 1.0259      | 1.7463      | 5.44017     | 1.7362      |
| 43  |      | Base (μs)         | 3.04325     | 4.981       | 21.15       | 5.9572      |
| 44  |      | max error         | 3.88578e-16 | 7.49867e-10 | 3.6318e-13  | 1.63653e-10 |
| 45  | 12   | compile time (s)  | 1.67744     | 1.68932     | 6.86415     | 0.634561    |
| 46  |      | StaticArrays (μs) | 1.3095      | 2.19967     | 6.883       | 2.18744     |
| 47  |      | Base (μs)         | 3.1435      | 5.32        | 15.389      | 6.2838      |
| 48  |      | max error         | 3.33067e-16 | 1.01178e-9  | 7.62294e-13 | 4.72728e-6  |
| 49  | 13   | compile time (s)  | 1.97382     | 2.29332     | 8.89459     | 0.934441    |
| 50  |      | StaticArrays (μs) | 1.6742      | 2.84089     | 8.67967     | 2.80078     |
| 51  |      | Base (μs)         | 4.12057     | 5.27        | 24.336      | 7.83133     |
| 52  |      | max error         | 3.60822e-16 | 3.06425e-8  | 1.84246e-12 | 2.18841e-9  |
| 53  | 14   | compile time (s)  | 2.32201     | 3.0074      | 11.0459     | 1.24842     |
| 54  |      | StaticArrays (μs) | 2.10511     | 3.47275     | 10.6        | 3.55537     |
| 55  |      | Base (μs)         | 6.0576      | 8.31567     | 19.256      | 10.349      |
| 56  |      | max error         | 3.88578e-16 | 1.22664e-9  | 2.66985e-12 | 8.79848e-6  |
| 57  | 15   | compile time (s)  | 0.0116938   | 0.0807205   | 16.3971     | 0.0608353   |
| 58  |      | StaticArrays (μs) | 4.6326      | 9.2675      | 24.075      | 11.011      |
| 59  |      | Base (μs)         | 4.8512      | 8.255       | 25.148      | 12.985      |
| 60  |      | max error         | 0.0         | 0.0         | 6.03259e-12 | 0.0         |
| 61  | 16   | compile time (s)  | 0.0120915   | 0.0786682   | 19.5899     | 0.072642    |
| 62  |      | StaticArrays (μs) | 7.399       | 9.929       | 45.606      | 12.915      |
| 63  |      | Base (μs)         | 5.40533     | 9.43767     | 32.251      | 11.422      |
| 64  |      | max error         | 0.0         | 0.0         | 9.3094e-12  | 0.0         |
| 65  | 17   | compile time (s)  | 0.0116415   | 0.101846    | 23.9458     | 0.0833374   |
| 66  |      | StaticArrays (μs) | 6.58567     | 9.087       | 60.273      | 14.006      |
| 67  |      | Base (μs)         | 6.1636      | 10.66       | 36.018      | 15.971      |
| 68  |      | max error         | 0.0         | 0.0         | 1.3546e-11  | 0.0         |
| 69  | 18   | compile time (s)  | 0.0220179   | 0.0982824   | 27.7817     | 0.0838804   |
| 70  |      | StaticArrays (μs) | 10.49       | 18.034      | 49.874      | 16.441      |
| 71  |      | Base (μs)         | 13.0772     | 12.854      | 55.054      | 12.774      |
| 72  |      | max error         | 0.0         | 0.0         | 2.21016e-11 | 0.0         |
| 73  | 19   | compile time (s)  | 0.0113863   | 0.123696    | 33.5317     | 0.0891655   |
| 74  |      | StaticArrays (μs) | 10.51       | 14.457      | 73.799      | 14.818      |
| 75  |      | Base (μs)         | 10.6533     | 13.886      | 44.754      | 12.664      |
| 76  |      | max error         | 0.0         | 0.0         | 4.0297e-11  | 0.0         |
| 77  | 20   | compile time (s)  | 0.0120176   | 0.122464    | 39.633      | 0.099849    |
| 78  |      | StaticArrays (μs) | 10.8        | 16.491      | 59.623      | 18.706      |
| 79  |      | Base (μs)         | 10.4        | 14.849      | 49.393      | 18.264      |
| 80  |      | max error         | 0.0         | 0.0         | 1.8213e-11  | 0.0         |

The compile time does continue to increase for `expm` past 14x14 matrices (my new pet theory: the `ldiv` methods in [triangular.jl](https://github.com/JuliaArrays/StaticArrays.jl/blob/c55193b1bb78b37330a7530b02c6e16e61dab537/src/triangular.jl) never dispatch to `Base`).

> doesn't mul! call BLAS directly for large matrices?

Oh yes, that's correct: https://github.com/JuliaArrays/StaticArrays.jl/blob/master/src/matrix_multiply.jl#L126.

**Comment by martinholters** [comment]
Little experiment concerning the LU implementation (and sorry for hijacking this PR):
```julia
function mylu(A::StaticMatrix{T}, ::Val{Pivot}=Val(true)) where {T,Pivot}
    A = MMatrix(A)
    m, n = size(A)
    ipiv = MVector{m,Int}()

    minmn = min(m,n)

    @inbounds begin # this whole loop copied from stdlib/LinearAlgebra/src/lu.jl
        for k = 1:minmn
            # find index max
            kp = k
            if Pivot
                amax = abs(zero(T))
                for i = k:m
                    absi = abs(A[i,k])
                    if absi > amax
                        kp = i
                        amax = absi
                    end
                end
            end
            ipiv[k] = kp
            if !iszero(A[kp,k])
                if k != kp
                    # Interchange
                    for i = 1:n
                        tmp = A[k,i]
                        A[k,i] = A[kp,i]
                        A[kp,i] = tmp
                    end
                end
                # Scale first column
                Akkinv = inv(A[k,k])
                for i = k+1:m
                    A[i,k] *= Akkinv
                end
            elseif info == 0
                info = k
            end
            # Update the rest
            for j = k+1:n
                for i = k+1:m
                    A[i,j] -= A[i,k]*A[k,j]
                end
            end
        end
    end

    return SMatrix(A), SVector(ipiv)
end
```

Then I get (on 0.7.0-alpha.0):
```julia
julia> @btime mylu($(SMatrix{10,10}(rand(10,10))));
  606.908 ns (0 allocations: 0 bytes)
```
Compare with (on 0.6.3; cannot meaningfully bechmark on 0.7 due to deprecations):
```julia
julia> @btime StaticArrays.__lu($(SMatrix{10,10}(rand(10,10))), Val{true});
  652.778 ns (0 allocations: 0 bytes)
```
It's not a 100% fair comparison (results in slightly different formats, different Julia versions, runtime depends on random values (different pivoting), ...), but they're definitely close. And approximately ten times faster than `lu($(rand(10,10)))`.

However, on 0.6.3, i.e. without the allocation elimination:
```julia
julia> @btime mylu($(SMatrix{10,10}(rand(10,10))));
  138.708 μs (2505 allocations: 57.20 KiB)
```

**Pull request merged**
